In [ ]:

## Session 2 - Intro to Python

In [ ]:
import pandas as pd
import numpy as np


data = [
    ["2025-01-02", "Cardiology",     "Hypertension", 67, 142, 92],
    ["2025-01-03", "PrimaryCare",    "Diabetes",     54, 128, 84],
    ["2025-01-04", "Cardiology",     "Arrhythmia",   72, 150, 95],
    ["2025-01-05", "Endocrinology",  "Diabetes",     49, 132, 86],
    ["2025-01-06", "PrimaryCare",    "Checkup",      36, 118, 76],
    ["2025-01-07", "Cardiology",     "Hypertension", 61, 146, 94],
]

df = pd.DataFrame(
    data,
    columns=[
        "visit_date",
        "department",
        "diagnosis",
        "patient_age",
        "systolic_bp",
        "diastolic_bp"
    ]
)

# convert to date type
df["visit_date"] = pd.to_datetime(df["visit_date"])


# df short cut for dataframe
# dataframes are excel sheets inside Python

df

,visit_date,department,diagnosis,patient_age,systolic_bp,diastolic_bp
0,2025-01-02,Cardiology,Hypertension,67,142,92
1,2025-01-03,PrimaryCare,Diabetes,54,128,84
2,2025-01-04,Cardiology,Arrhythmia,72,150,95
3,2025-01-05,Endocrinology,Diabetes,49,132,86
4,2025-01-06,PrimaryCare,Checkup,36,118,76
5,2025-01-07,Cardiology,Hypertension,61,146,94

In [ ]:
# human readable note.
# Python will ignore it and will not execute it

df

,visit_date,department,diagnosis,patient_age,systolic_bp,diastolic_bp
0,2025-01-02,Cardiology,Hypertension,67,142,92
1,2025-01-03,PrimaryCare,Diabetes,54,128,84
2,2025-01-04,Cardiology,Arrhythmia,72,150,95
3,2025-01-05,Endocrinology,Diabetes,49,132,86
4,2025-01-06,PrimaryCare,Checkup,36,118,76
5,2025-01-07,Cardiology,Hypertension,61,146,94

In [ ]:
# I would want to only take a look at the departments I have in my dataframe (excel sheet):
# Give me my df first, then give me the column name:

# Syntax: excelsheetname['column_name']
df['department']

0       Cardiology
1      PrimaryCare
2       Cardiology
3    Endocrinology
4      PrimaryCare
5       Cardiology
Name: department, dtype: object

In [ ]:
 # function: a command that will do a specific task for you

# average patient age is 56.5 years old
# float: decimals

patient_average_age = df["patient_age"].mean()

print("The average age of all patients is: ", patient_average_age)

The average age of all patients is:  56.5

In [ ]:
df["patient_age"]

0    67
1    54
2    72
3    49
4    36
5    61
Name: patient_age, dtype: int64

In [ ]:
# this will add 10 into every single number in your patient_age column

patient_age_plus_ten = df["patient_age"] + 10

print(patient_age_plus_ten)

0    77
1    64
2    82
3    59
4    46
5    71
Name: patient_age, dtype: int64

In [ ]:
df

,visit_date,department,diagnosis,patient_age,systolic_bp,diastolic_bp
0,2025-01-02,Cardiology,Hypertension,67,142,92
1,2025-01-03,PrimaryCare,Diabetes,54,128,84
2,2025-01-04,Cardiology,Arrhythmia,72,150,95
3,2025-01-05,Endocrinology,Diabetes,49,132,86
4,2025-01-06,PrimaryCare,Checkup,36,118,76
5,2025-01-07,Cardiology,Hypertension,61,146,94

In [ ]:
add_sp_dp = df["systolic_bp"] + df["diastolic_bp"]

add_sp_dp

0    234
1    212
2    245
3    218
4    194
5    240
dtype: int64

In [ ]:
df

,visit_date,department,diagnosis,patient_age,systolic_bp,diastolic_bp
0,2025-01-02,Cardiology,Hypertension,67,142,92
1,2025-01-03,PrimaryCare,Diabetes,54,128,84
2,2025-01-04,Cardiology,Arrhythmia,72,150,95
3,2025-01-05,Endocrinology,Diabetes,49,132,86
4,2025-01-06,PrimaryCare,Checkup,36,118,76
5,2025-01-07,Cardiology,Hypertension,61,146,94

In [ ]:

# Here I am going to create a new column in my dataframe and I will call it 'total_blood_pressure'

df['total_blood_pressure'] = df['systolic_bp'] + df['diastolic_bp']

df

,visit_date,department,diagnosis,patient_age,systolic_bp,diastolic_bp,total_blood_pressure
0,2025-01-02,Cardiology,Hypertension,67,142,92,234
1,2025-01-03,PrimaryCare,Diabetes,54,128,84,212
2,2025-01-04,Cardiology,Arrhythmia,72,150,95,245
3,2025-01-05,Endocrinology,Diabetes,49,132,86,218
4,2025-01-06,PrimaryCare,Checkup,36,118,76,194
5,2025-01-07,Cardiology,Hypertension,61,146,94,240

In [ ]:
# Variables in Python:

# define variables: something that changes. Something that varies from value to another

# When you define a categorical column/variable in Python, it must be inside a single or double quotes

Khaled_Age = 33

Charlie_city = 'NY'


# I represented the column of patients_age as a list of numbers
# so my variable name patients_age is technically a column representing the ages list

Patient_names = ['Khaled', 'John', 'Mike', 'Jamal']
patients_age = [67, 54, 72, 49]

In [ ]:
print(Khaled_Age) # type of: Khaled_Age variable (numeric)

print(Charlie_city) # type is categorical

print(patients_age) # list of numeric values

33
NY
[67, 54, 72, 49]

In [ ]:
# document it:

# What does this code do? and why do you need it for your business?

In [ ]:
mylist = []
mylist.append(1)
mylist.append(2)
mylist.append(3)
print(mylist[0]) # prints 1
print(mylist[1]) # prints 2
print(mylist[2]) # prints 3

# prints out 1,2,3
for x in mylist:
    print(x)

1
2
3
1
2
3

In [ ]:
# Sesson 3 - Functions and If Statements:

In [1]:
# This function takes a name as input
def greet_user(name):
    # name is a variable given to the function
    print("Hello", name)

# Call the function with a value
greet_user("Nada")
greet_user("Alex")

Hello Nada
Hello Alex

In [2]:
# This function adds two numbers
def add_numbers(a, b):
    # We calculate the sum
    total = a + b

    # return sends the result back
    return total

# Store the result in a variable
result = add_numbers(3, 5)

# Print the result
print(result)


# 	•	print() shows something
#   •	return gives something back

8

In [8]:
# This function checks if a number is positive
def check_positive(number):
    # if condition checks a rule
    if number > 0:
        print("The number is positive")
    else:
      print("The number is negative or 0")

# Call the function
check_positive(10)
check_positive(-5)

The number is positive
The number is negative or 0

In [4]:
# This function checks a student's grade
def check_grade(score):
    if score >= 90:
        print("Grade: A")
    elif score >= 70:
        print("Grade: B")
    else:
        print("Grade: C")

# Call the function
check_grade(95)
check_grade(80)
check_grade(60)

Grade: A
Grade: B
Grade: C

In [ ]:
# Excercise:
'''
Task 1:
Write a function called total_price(price, quantity) that returns the total cost.

Example:
	•	price = 5
	•	quantity = 3
	•	result = 15


Task 2:
Write a function called traffic_light(color) that:
	•	prints "Stop" if the color is "red"
	•	prints "Go" otherwise
'''

In [ ]:
# Topic 3: If Else Statements (Conditions)

# Introduction to `if` Conditionals in Python

This lesson explains **`if` conditionals** in a very simple and beginner-friendly way.

---

## What is an `if` conditional?

An `if` conditional lets a program **make a decision**.

In simple words, it means:

> **If something is true, do this.**

If it is not true, the program can do something else.

---

## How an `if` statement works

Python checks a **condition**.

- If the condition is **True** → the code runs  
- If the condition is **False** → the code is skipped  

---

## Basic structure of an `if` statement

```python
if condition:
    # code that runs if the condition is True

In [9]:
number = 5

if number > 0:
    print("The number is positive")

The number is positive

In [ ]:
number = -3

if number > 0:
    print("Positive")
else:
    print("Negative or zero")

In [ ]:
score = 75

if score >= 90:
    print("Grade A")
elif score >= 70:
    print("Grade B")
else:
    print("Grade C")

In [10]:
hour = 10

if hour >= 9 and hour <= 17:
    print("Store is open")
else:
    print("Store is closed")

Store is open

In [11]:
# Rock, Paper, Scissors game

# Player chooses one option
player = input("Choose rock, paper, or scissors: ")

# Computer choice (hardcoded for now to keep it simple)
computer = "scissors"

# Show choices
print("Player chose:", player)
print("Computer chose:", computer)

# First, check if it is a tie
if player == computer:
    print("It's a tie!")

else:
    # Player chooses rock
    if player == "rock":
        if computer == "scissors":
            print("Rock beats scissors. You win!")
        else:
            print("Paper beats rock. You lose.")

    # Player chooses paper
    elif player == "paper":
        if computer == "rock":
            print("Paper beats rock. You win!")
        else:
            print("Scissors beats paper. You lose.")

    # Player chooses scissors
    elif player == "scissors":
        if computer == "paper":
            print("Scissors beats paper. You win!")
        else:
            print("Rock beats scissors. You lose.")

    # If the player enters something invalid
    else:
        print("Invalid choice. Please choose rock, paper, or scissors.")

Choose rock, paper, or scissors: paper
Player chose: paper
Computer chose: scissors
Scissors beats paper. You lose.

In [12]:
'''
Task:
Write code that checks if a number is greater than 10.
	•	If yes, print "Big number"
	•	Else, print "Small number"


'''

'\nTask:\nWrite code that checks if a number is greater than 10.\n\t•\tIf yes, print "Big number"\n\t•\tElse, print "Small number"\n\n  \n'