In [ ]:

## Session 2 - Intro to Python

In [ ]:
import pandas as pd
import numpy as np


data = [
    ["2025-01-02", "Cardiology",     "Hypertension", 67, 142, 92],
    ["2025-01-03", "PrimaryCare",    "Diabetes",     54, 128, 84],
    ["2025-01-04", "Cardiology",     "Arrhythmia",   72, 150, 95],
    ["2025-01-05", "Endocrinology",  "Diabetes",     49, 132, 86],
    ["2025-01-06", "PrimaryCare",    "Checkup",      36, 118, 76],
    ["2025-01-07", "Cardiology",     "Hypertension", 61, 146, 94],
]

df = pd.DataFrame(
    data,
    columns=[
        "visit_date",
        "department",
        "diagnosis",
        "patient_age",
        "systolic_bp",
        "diastolic_bp"
    ]
)

# convert to date type
df["visit_date"] = pd.to_datetime(df["visit_date"])


# df short cut for dataframe
# dataframes are excel sheets inside Python

df

,visit_date,department,diagnosis,patient_age,systolic_bp,diastolic_bp
0,2025-01-02,Cardiology,Hypertension,67,142,92
1,2025-01-03,PrimaryCare,Diabetes,54,128,84
2,2025-01-04,Cardiology,Arrhythmia,72,150,95
3,2025-01-05,Endocrinology,Diabetes,49,132,86
4,2025-01-06,PrimaryCare,Checkup,36,118,76
5,2025-01-07,Cardiology,Hypertension,61,146,94

In [ ]:
# human readable note.
# Python will ignore it and will not execute it

df

,visit_date,department,diagnosis,patient_age,systolic_bp,diastolic_bp
0,2025-01-02,Cardiology,Hypertension,67,142,92
1,2025-01-03,PrimaryCare,Diabetes,54,128,84
2,2025-01-04,Cardiology,Arrhythmia,72,150,95
3,2025-01-05,Endocrinology,Diabetes,49,132,86
4,2025-01-06,PrimaryCare,Checkup,36,118,76
5,2025-01-07,Cardiology,Hypertension,61,146,94

In [ ]:
# I would want to only take a look at the departments I have in my dataframe (excel sheet):
# Give me my df first, then give me the column name:

# Syntax: excelsheetname['column_name']
df['department']

0       Cardiology
1      PrimaryCare
2       Cardiology
3    Endocrinology
4      PrimaryCare
5       Cardiology
Name: department, dtype: object

In [ ]:
 # function: a command that will do a specific task for you

# average patient age is 56.5 years old
# float: decimals

patient_average_age = df["patient_age"].mean()

print("The average age of all patients is: ", patient_average_age)

The average age of all patients is:  56.5

In [ ]:
df["patient_age"]

0    67
1    54
2    72
3    49
4    36
5    61
Name: patient_age, dtype: int64

In [ ]:
# this will add 10 into every single number in your patient_age column

patient_age_plus_ten = df["patient_age"] + 10

print(patient_age_plus_ten)

0    77
1    64
2    82
3    59
4    46
5    71
Name: patient_age, dtype: int64

In [ ]:
df

,visit_date,department,diagnosis,patient_age,systolic_bp,diastolic_bp
0,2025-01-02,Cardiology,Hypertension,67,142,92
1,2025-01-03,PrimaryCare,Diabetes,54,128,84
2,2025-01-04,Cardiology,Arrhythmia,72,150,95
3,2025-01-05,Endocrinology,Diabetes,49,132,86
4,2025-01-06,PrimaryCare,Checkup,36,118,76
5,2025-01-07,Cardiology,Hypertension,61,146,94

In [ ]:
add_sp_dp = df["systolic_bp"] + df["diastolic_bp"]

add_sp_dp

0    234
1    212
2    245
3    218
4    194
5    240
dtype: int64

In [ ]:
df

,visit_date,department,diagnosis,patient_age,systolic_bp,diastolic_bp
0,2025-01-02,Cardiology,Hypertension,67,142,92
1,2025-01-03,PrimaryCare,Diabetes,54,128,84
2,2025-01-04,Cardiology,Arrhythmia,72,150,95
3,2025-01-05,Endocrinology,Diabetes,49,132,86
4,2025-01-06,PrimaryCare,Checkup,36,118,76
5,2025-01-07,Cardiology,Hypertension,61,146,94

In [ ]:

# Here I am going to create a new column in my dataframe and I will call it 'total_blood_pressure'

df['total_blood_pressure'] = df['systolic_bp'] + df['diastolic_bp']

df

,visit_date,department,diagnosis,patient_age,systolic_bp,diastolic_bp,total_blood_pressure
0,2025-01-02,Cardiology,Hypertension,67,142,92,234
1,2025-01-03,PrimaryCare,Diabetes,54,128,84,212
2,2025-01-04,Cardiology,Arrhythmia,72,150,95,245
3,2025-01-05,Endocrinology,Diabetes,49,132,86,218
4,2025-01-06,PrimaryCare,Checkup,36,118,76,194
5,2025-01-07,Cardiology,Hypertension,61,146,94,240

In [ ]:
# Variables in Python:

# define variables: something that changes. Something that varies from value to another

# When you define a categorical column/variable in Python, it must be inside a single or double quotes

Khaled_Age = 33

Charlie_city = 'NY'


# I represented the column of patients_age as a list of numbers
# so my variable name patients_age is technically a column representing the ages list

Patient_names = ['Khaled', 'John', 'Mike', 'Jamal']
patients_age = [67, 54, 72, 49]

In [ ]:
print(Khaled_Age) # type of: Khaled_Age variable (numeric)

print(Charlie_city) # type is categorical

print(patients_age) # list of numeric values

33
NY
[67, 54, 72, 49]

In [ ]:
# document it:

# What does this code do? and why do you need it for your business?

In [ ]:
mylist = []
mylist.append(1)
mylist.append(2)
mylist.append(3)
print(mylist[0]) # prints 1
print(mylist[1]) # prints 2
print(mylist[2]) # prints 3

# prints out 1,2,3
for x in mylist:
    print(x)

1
2
3
1
2
3

In [ ]:
# Sesson 3 - Functions and If Statements:

In [ ]:

# define a function: a reusable piece of code that can do a certain task for you.
# use the functions already written for us, or we can create our own functions

# example of functions: mean() --> calculates the avg for any list of number you give it.
# median(), count()

In [ ]:

# to start buulding your function, define it first and give it a name:

def functionname(variable that will change):
  # whatever the function needs to do
  # whatever you want the function to do for that variable that will change

In [ ]:

# write a function that wishes you happy birthday for any given name (variable)

def happy_birthday(name):
  print("Happy birthday to you!", name)
  print("Happy birthday to you!")
  print("Happy birthday, dear", name)
  print("Happy birthday to you!")


# now I can call the function:
name  = 'Barbara'

happy_birthday(name)

Happy birthday to you! Barbara
Happy birthday to you!
Happy birthday, dear Barbara
Happy birthday to you!

In [ ]:

# Define the function called add_numbers that will add two numbers:
def add_numbers(first_number, second_number):
  total = first_number + second_number
  return total

# use and call the function:

# first_number = put("Enter the first number: ")
# second_number = put("Enter the second number: ")


add_numbers(5,100)

105

In [ ]:
# This function takes a name as input
def greet_user(name):
    # name is a variable given to the function
    print("Hello", name)

# Call the function with a value
greet_user("Nada")
greet_user("Alex")

Hello Nada
Hello Alex

In [ ]:
# This function adds two numbers
def add_numbers(a, b):
    # We calculate the sum
    total = a + b

    # return sends the result back
    return total

# Store the result in a variable
result = add_numbers(3, 5)

# Print the result
print(result)


# 	•	print() shows something
#   •	return gives something back

8

In [ ]:
# This function checks if a number is positive
def check_positive(number):
    # if condition checks a rule
    if number > 0:
        print("The number is positive")
    else:
      print("The number is negative or 0")

In [ ]:

# Call the function
check_positive(10)
check_positive(-5)

The number is positive
The number is negative or 0

In [ ]:
# This function checks a student's grade
def check_grade(score):
    if score >= 90:
        print("Grade: A")
    elif score >= 70:
        print("Grade: B")
    else:
        print("Grade: C")

# Call the function
check_grade(95)
check_grade(80)
check_grade(60)

Grade: A
Grade: B
Grade: C

In [ ]:
# Excercise:
'''
Task 1:
Write a function called total_price(price, quantity) that returns the total cost.

Example:
	•	price = 5
	•	quantity = 3
	•	result = 15


Task 2:
Write a function called traffic_light(color) that:
	•	prints "Stop" if the color is "red"
	•	prints "Go" otherwise
'''

In [ ]:
# Topic 3: If Else Statements (Conditions)

# Introduction to `if` Conditionals in Python

This lesson explains **`if` conditionals** in a very simple and beginner-friendly way.

---

## What is an `if` conditional?

An `if` conditional lets a program **make a decision**.

In simple words, it means:

> **If something is true, do this.**

If it is not true, the program can do something else.

---

## How an `if` statement works

Python checks a **condition**.

- If the condition is **True** → the code runs  
- If the condition is **False** → the code is skipped  

---

## Basic structure of an `if` statement

```python
if condition:
    # code that runs if the condition is True

In [ ]:

# I created a variable called 'number' and I assigned it a value which is 5
number = 7

# the if statement will CHECK first before it run if that condition is TRUE or FALSE.
# It will only execute if the condition is TRUE

if number > 0:
    print("The number is positive")

The number is positive

In [ ]:


# I created a variable called 'number' and I assigned it a value which is 5
number = -1

# the if statement will CHECK first before it run if that condition is TRUE or FALSE.
# It will only execute if the condition is TRUE

if number > 0: # FALSE I will skip it and move on to the else stateemnt
    print("The number is positive")
else:  # is number <0 if TRUE execute
  print("The number of negative")

The number of negative

In [ ]:
number = 100

if number > 0:
    print(number, "The number is positive")
# == in python means 'IS' , 'SAME VALUE AS':
elif number == 0:
  print(number, "The number is zero")
elif number == 100:
  print(number, 'that number is 100')
else:
  print(number, "The number is negative")

100 The number is positive

In [ ]:
product = 'laptop'.lower()

if product == 'laptop':
    print('Product Category is: Technology')
elif product == 'glasses':
  print('Product Category is: Accessories')
elif product == 'phone':
  print('Product Category is: Electronics')
else:
  print('No category found')

Product Category is: Technology

In [ ]:


product = 'LAPTOP'.lower()

if product == 'laptop':
    print('Product Category is: Technology')
elif product == 'glasses':
  print('Product Category is: Accessories')
elif product == 'phone':
  print('Product Category is: Electronics')
else:
  print('No category found')

Product Category is: Technology

In [ ]:
if number % 2 == 0:
    print("The number is even")
else:
    print("The number is odd")

The number is even

In [ ]:
number = -3

if number > 0:
    print("Positive")
else:
    print("Negative or zero")

In [ ]:
score = 75

if score >= 90:
    print("Grade A")
elif score >= 70:
    print("Grade B")
else:
    print("Grade C")

In [ ]:
hour = 10

# NESTED If Statements:

if hour >= 9 and hour <= 17:
    print("Store is open")
else:
    print("Store is closed")

Store is open

In [ ]:
hour = 10

# NESTED If Statements (if statement inside another if statement):
if hour >= 9 and hour <= 17:
    print("Store is open")
else:
    print("Store is closed")

In [ ]:
# Rock, Paper, Scissors game

# Player chooses one option
player = input("Choose rock, paper, or scissors: ")

# Computer choice (hardcoded for now to keep it simple)
computer = "scissors"

# Show choices
print("Player chose:", player)
print("Computer chose:", computer)

# First, check if it is a tie
if player == computer:
    print("It's a tie!")
else:
    # Player chooses rock
    if player == "rock":
        if computer == "scissors":
            print("Rock beats scissors. You win!")
        else:
            print("Paper beats rock. You lose.")

    # Player chooses paper
    elif player == "paper":
        if computer == "rock":
            print("Paper beats rock. You win!")
        else:
            print("Scissors beats paper. You lose.")

    # Player chooses scissors
    elif player == "scissors":
        if computer == "paper":
            print("Scissors beats paper. You win!")
        else:
            print("Rock beats scissors. You lose.")

    # If the player enters something invalid
    else:
        print("Invalid choice. Please choose rock, paper, or scissors.")

Choose rock, paper, or scissors: scissors
Player chose: scissors
Computer chose: scissors
It's a tie!

In [ ]:
'''
Task:
Write code that checks if a number is greater than 10.
	•	If yes, print "Big number"
	•	Else, print "Small number"
print the number itself inside the print statement

'''

'\nTask:\nWrite code that checks if a number is greater than 10.\n\t•\tIf yes, print "Big number"\n\t•\tElse, print "Small number"\n\n  \n'

In [ ]:
# Lists:

# Create a list
nums = [10, 20, 30]

# Access items (index starts at 0)
print(nums[0])   # first item
print(nums[2])   # third item

# Add item to end
nums.append(40)
print(nums)

# Insert at position
nums.insert(1, 15)
print(nums)

# Remove item
nums.remove(20)
print(nums)

# Length of list
print(len(nums))

# Loop through list
for n in nums:
    print(n)

10
30
[10, 20, 30, 40]
[10, 15, 20, 30, 40]
[10, 15, 30, 40]
4
10
15
30
40

### Session 4 - Lists, Dictionaries, Loop:

### Lists:

In [ ]:

# A LIST is a container that stores multiple values in order
# Think of it like a shopping list or a list of scores

# -----------------------------
# Creating lists
# -----------------------------

numbers = [10, 20, 30, 40]          # list of numbers
fruits = ["apple", "banana", "orange"]  # list of strings

print(numbers)   # print the whole list
print(fruits)

# -----------------------------
# Accessing list items
# -----------------------------

print(numbers[0])   # first item (index starts at 0)
print(numbers[1])   # second item
print(numbers[-1])  # last item in the list

# -----------------------------
# Changing list values
# -----------------------------

numbers[0] = 15     # change the first value
print(numbers)

# -----------------------------
# Adding items to a list
# -----------------------------

numbers.append(50)  # add a value to the end of the list
print(numbers)

numbers.insert(1, 12)  # insert a value at position 1
print(numbers)

# -----------------------------
# Removing items from a list
# -----------------------------

numbers.remove(30)  # remove the value 30
print(numbers)

numbers.pop()       # remove the last item
print(numbers)

# -----------------------------
# List length
# -----------------------------

print(len(numbers))  # number of items in the list

# -----------------------------
# Checking if a value exists
# -----------------------------

print(20 in numbers)  # True if 20 is in the list
print(99 in numbers)  # False if 99 is not in the list

# -----------------------------
# Sorting and reversing lists
# -----------------------------

numbers.sort()      # sort values from smallest to largest
print(numbers)

numbers.reverse()   # reverse the order
print(numbers)

# -----------------------------
# Looping through a list
# -----------------------------

for n in numbers:
    print(n)        # print each value one by one

# -----------------------------
# Real example: calculating total and average
# -----------------------------

sales = [100, 200, 150, 300]  # daily sales values

total_sales = 0              # start total at 0

for s in sales:
    total_sales += s         # add each sale to total

average_sales = total_sales / len(sales)  # calculate average

print("Total sales:", total_sales)
print("Average sales:", average_sales)

[10, 20, 30, 40]
['apple', 'banana', 'orange']
10
20
40
[15, 20, 30, 40]
[15, 20, 30, 40, 50]
[15, 12, 20, 30, 40, 50]
[15, 12, 20, 40, 50]
[15, 12, 20, 40]
4
True
False
[12, 15, 20, 40]
[40, 20, 15, 12]
40
20
15
12
Total sales: 750
Average sales: 187.5

### Dictionaries:

In [ ]:
# A DICTIONARY can store lists as values
# This is very common in real data work
# Think of it like a table:
# key = column name
# value = list of data in that column

# -----------------------------
# Creating a dictionary with lists
# -----------------------------

student_scores = {
    "math": [80, 85, 90],
    "science": [78, 88, 92],
    "english": [75, 82, 89]
}

print(student_scores)  # print the whole dictionary

# -----------------------------
# Accessing a list using a key
# -----------------------------

print(student_scores["math"])      # get all math scores
print(student_scores["science"])   # get all science scores

# -----------------------------
# Accessing individual values inside the list
# -----------------------------

print(student_scores["math"][0])   # first math score
print(student_scores["english"][-1])  # last english score

# -----------------------------
# Adding values to a list inside the dictionary
# -----------------------------

student_scores["math"].append(95)   # add a new math score
student_scores["science"].append(90)

print(student_scores)

# -----------------------------
# Updating values inside lists
# -----------------------------

student_scores["english"][1] = 85   # change second english score
print(student_scores)

# -----------------------------
# Removing values from a list
# -----------------------------

student_scores["math"].remove(80)   # remove score 80 from math
print(student_scores)

# -----------------------------
# Adding a new key with a list
# -----------------------------

student_scores["history"] = [70, 75, 80]
print(student_scores)

# -----------------------------
# Removing a key and its list
# -----------------------------

student_scores.pop("science")        # remove science scores
print(student_scores)

# -----------------------------
# Checking if a key exists
# -----------------------------

print("math" in student_scores)      # True
print("biology" in student_scores)   # False

# -----------------------------
# Looping through dictionary and lists
# -----------------------------

for subject, scores in student_scores.items():
    print(subject, scores)

# -----------------------------
# Real example: calculate average score per subject
# -----------------------------

for subject, scores in student_scores.items():
    total = 0

    for s in scores:
        total += s

    average = total / len(scores)
    print(subject, "average:", average)

{'math': [80, 85, 90], 'science': [78, 88, 92], 'english': [75, 82, 89]}
[80, 85, 90]
[78, 88, 92]
80
89
{'math': [80, 85, 90, 95], 'science': [78, 88, 92, 90], 'english': [75, 82, 89]}
{'math': [80, 85, 90, 95], 'science': [78, 88, 92, 90], 'english': [75, 85, 89]}
{'math': [85, 90, 95], 'science': [78, 88, 92, 90], 'english': [75, 85, 89]}
{'math': [85, 90, 95], 'science': [78, 88, 92, 90], 'english': [75, 85, 89], 'history': [70, 75, 80]}
{'math': [85, 90, 95], 'english': [75, 85, 89], 'history': [70, 75, 80]}
True
False
math [85, 90, 95]
english [75, 85, 89]
history [70, 75, 80]
math average: 90.0
english average: 83.0
history average: 75.0

### For Loops:

In [ ]:
# A LOOP repeats code automatically
# Instead of writing the same code many times, Python does it for you

# =========================================================
# FOR LOOPS
# =========================================================

# A FOR loop is used when you KNOW what you are looping over
# Example: a list of numbers

numbers = [10, 20, 30, 40]

# How to think about a FOR loop:
# START: first item in the list
# MIDDLE: keep going through each item
# END: stop when there are no more items

for n in numbers:
    print(n)   # this runs once for EACH item in the list

# ---------------------------------------------------------
# FOR loop with range()
# ---------------------------------------------------------

# range(5) creates numbers from 0 to 4
# START: 0
# END: stops before 5
# STEP (increment): +1 by default

for i in range(5):
    print(i)

# ---------------------------------------------------------
# FOR loop with start and end
# ---------------------------------------------------------

# range(start, end)
# START: 1
# END: stops before 6
# STEP: +1

for i in range(1, 6):
    print(i)

# ---------------------------------------------------------
# FOR loop with step (increment)
# ---------------------------------------------------------

# range(start, end, step)
# START: 0
# END: stops before 10
# STEP: increase by 2

for i in range(0, 10, 2):
    print(i)

# =========================================================
# REAL EXAMPLE: TOTAL AND AVERAGE
# =========================================================

sales = [100, 200, 150, 300]

total = 0  # START: total begins at 0

# MIDDLE: loop through each sale
for s in sales:
    total += s  # INCREMENT: add current sale to total

# END: loop stops after last value
average = total / len(sales)

print("Total:", total)
print("Average:", average)

# =========================================================
# WHILE LOOPS
# =========================================================

# A WHILE loop is used when you DO NOT KNOW how many times it will run
# It keeps running as long as a condition is True

# How to think about a WHILE loop:
# START: initialize a variable
# CONDITION: check if we should continue
# INCREMENT: change the variable
# END: condition becomes False

count = 0  # START

while count < 5:  # CONDITION
    print(count)
    count += 1    # INCREMENT (VERY IMPORTANT)

# END: loop stops when count is no longer < 5

# ---------------------------------------------------------
# WHAT HAPPENS IF YOU FORGET INCREMENT?
# ---------------------------------------------------------

# If count += 1 is missing, the loop never ends
# This is called an INFINITE LOOP

# =========================================================
# REAL EXAMPLE: WAITING FOR VALID INPUT
# =========================================================

password = ""  # START

while password != "python":  # CONDITION
    password = input("Enter password: ")  # user input changes value

# END: loop stops when password equals "python"
print("Access granted")

# =========================================================
# COMBINING DICTIONARIES AND LOOPS
# =========================================================

student_scores = {
    "math": [80, 85, 90],
    "english": [75, 82, 88]
}

# Loop through dictionary
for subject, scores in student_scores.items():
    total = 0

    # Loop through list inside dictionary
    for s in scores:
        total += s

    average = total / len(scores)
    print(subject, "average:", average)

10
20
30
40
0
1
2
3
4
1
2
3
4
5
0
2
4
6
8
Total: 750
Average: 187.5
0
1
2
3
4
Enter password: s
Enter password: as
Enter password: Python
Enter password: python
Access granted
math average: 85.0
english average: 81.66666666666667

### Excercise:

In [ ]:
'''
Exercise 1: Modify a list

Create a list of three favorite movies.
Then:
	•	print the first movie
	•	add a new movie to the list
	•	remove one movie
	•	print the final list

'''

In [ ]:
'''
Exercise 2: Find the largest number

Given this list of numbers:

numbers = [45, 12, 89, 32, 67]

Write code to:
	•	find the largest number manually using a loop
	•	print the result

'''

In [ ]:
'''

Exercise 3:
You are given a list of daily temperatures.

temperatures = [55, 62, 70, 58, 65]

Write a for loop that:
	•	goes through each temperature
	•	checks if the value is greater than 60
	•	prints "Above 60" if it is
	•	prints "60 or below" if it is not


''''